demo0/demo1/booktest/urls.py
from django.conf.urls import url
from . import views

app_name = 'booktest'

# 绑定路由
urlpatterns = [
    # （URL， 绑定的视图函数）
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^list/$', views.list, name='list'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^deletehero/(\d+)/$', views.deletehero, name='deletehero'),
    url(r'^deletebook/(\d+)/$', views.deletebook, name='deletebook'),
    url(r'^addhero/(\d+)/$', views.addhero, name='addhero'),
    url(r'^addbook/$', views.addbook, name='addbook'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^verify/$', views.verify, name='verify'),

]

demo0/demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include



# 绑定路由
urlpatterns = [
    path('admin/', admin.site.urls),
    # （项目应用路由， 绑定应用路由下的子路由）
    url('', include('booktest.urls', namespace='booktest')),
    url('vote/', include('vote.urls', namespace='vote')),
]

demo0/demo1/vote/urls.py
from django.conf.urls import url
from . import views

app_name = 'vote'

urlpatterns = [
    url('^vindex/$', views.vindex, name='vindex'),
    url('^vdetail/(\d+)/$', views.vdetail, name='vdetail'),
    url('^result/(\d+)/$', views.result, name='result'),
    url('^login/$', views.login, name='login'),
    url('^logout/$', views.logout, name='logout'),
    url('^register/&', views.register, name='register'),
]

demo0/demo1/booktest/models.py
from django.db import models
from django.contrib.auth.models import User
# MVT中的M数据模型
# Create your models here.


class BookInfo(models.Model):
    title = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    pub_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class HeroInfoManage(models.Manager):
    def addhero(self, name, gender, content, book):
        hero = HeroInfo()
        hero.name = name
        hero.gender = gender
        hero.content = content
        hero.book = book
        hero.save()

class HeroInfo(models.Model):
    name = models.CharField(max_length=50)
    gender = models.CharField(max_length=10, choices=(('m','男'), ('w', '女')))
    # gender = models.BooleanField(default=True)
    content = models.CharField(max_length=100)
    book = models.ForeignKey(BookInfo, on_delete=models.CASCADE)
    objects = HeroInfoManage()
    def __str__(self):
        return self.name


class Ads(models.Model):
    desc = models.CharField(max_length=20)
    img = models.ImageField(upload_to='img')

    def __str__(self):
        return self.desc

demo0/demo1/booktest/views.py
import io
import random

from PIL import ImageDraw, Image, ImageFont
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.template import loader
from django.views.generic import View, TemplateView
from .models import HeroInfo, BookInfo, Ads
from .form import *
from django.core.cache import cache
from django.core.mail import send_mail
from django.conf import settings
# MVT 中核心V视图
# 接收请求，处理数据，返回响应
# Create your views here.






# 一个装饰器判断是否登录
def checklogin(fun):
    def check(request, *args):
        # 使用cookies
        # username = request.COOKIES.get('username')
        # 使用session
        username = request.session.get('username')
        if username:
            return fun(request, *args)
        else:
            return redirect(reverse('booktest:login'))
    return check


# 类视图
class IndexView(View):
    def get(self, request):

        ads = Ads.objects.all()
        # 使用cookie
        # username = request.COOKIES.get('username')
        # 使用session
        username = request.session.get('username')
        return render(request, 'booktest/index.html', {'username':username, 'ads': ads})


# 自定义视图函数
def index(request):
    # return HttpResponse('<h1>项目首页面</h1> <a href="/list/">列表页</a>')
    # temp1 = loader.get_template('booktest/index.html')
    # resutl = temp1.render({'username': 'chen'})
    # return HttpResponse(resutl)


    return render(request, 'booktest/index.html', {'username': 'chen'})


@checklogin
def list(request):
    # s="""
    #
    # <a href="/detail/1/">详情1</a>
    # <a href="/detail/2/">详情2</a>
    # <a href="/detail/3/">详情3</a>
    #
    # """
    # return HttpResponse('<h1>项目列表页</h1>%s'%(s, ))
    # temp2 = loader.get_template('booktest/list.html')
    # books = BookInfo.objects.all()
    # resutl = temp2.render({'books':books})
    # return HttpResponse(resutl)
    books = BookInfo.objects.all()
    return render(request, 'booktest/list.html', {'books': books})


@checklogin
def detail(request, id):
    # return HttpResponse('<h1>项目%s详情页</h1> <a href="/">首页</a>'%(id,))
    # temp3 = loader.get_template('booktest/detail.html')
    # book = BookInfo.objects.get(pk=id)
    # # pk表示主键，get表示查找主键为id的
    #
    # resutl = temp3.render({'book':book})
    # return HttpResponse(resutl)
    book = BookInfo.objects.get(pk=id)
    return render(request, 'booktest/detail.html', {'book': book})


@checklogin
def deletehero(request, id):
    hero = HeroInfo.objects.get(pk=id)
    bookid = hero.book.id
    hero.delete()
    # return HttpResponseRedirect('/detail/%s/'%(bookid, ))
    return redirect(reverse('booktest:detail', args=(bookid, )))


@checklogin
def deletebook(request, id):
    book = BookInfo.objects.get(pk=id)
    book.delete()
    return redirect(reverse('booktest:list'))


@checklogin
def addhero(request,id):
    book = BookInfo.objects.get(pk=id)
    if request.method == 'GET':
        return render(request, 'booktest/addhero.html', {'book':book})
    elif request.method == 'POST':
        name = request.POST.get('username')
        content = request.POST.get('content')
        gender = request.POST.get('gender')
        HeroInfo.objects.addhero(name, gender, content, book)
        # hero = HeroInfo()
        # hero.name = name
        # hero.gender = gender
        # hero.content = content
        # hero.book = book
        # hero.save()
        return redirect(reverse('booktest:detail', args=(book.id, )))


@checklogin
def addbook(request):
    if request.method == "GET":
        return render(request, 'booktest/addbook.html',{})
    elif request.method == 'POST':
        title = request.POST.get('title')
        book = BookInfo()
        book.title = title
        book.save()
        return redirect(reverse('booktest:list'))


@checklogin
def upload(request):
    if request.method == 'GET':
        return render(request, 'booktest/upload.html')
    elif request.method == 'POST':
        # 创建实例
        ads = Ads()
        # 获取HTML页面数据
        ads.desc = request.POST.get('desc')
        ads.img = request.FILES['uploadimg']
        ads.save()

        return redirect(reverse('booktest:index'))




def login(request):
    if request.method == 'GET':
        a = ['2271992921@qq.com']
        # send_mail('aa','12313', settings.EMAIL_HOST_USER,a)


        lgf = LoginForm()
        return render(request, 'booktest/login.html', {'lgf': lgf})
    elif request.method == 'POST':
        # 使用cookie
        # response = redirect(reverse('booktest:index'))
        # response.set_cookie('username', request.POST.get('username'))
        # return response

        # 使用session
        request.session['username'] = request.POST.get('username')
        code = cache.get('rand_str').lower()
        if request.POST.get('verifycode').lower() != code:
            return HttpResponse('验证码错误')
        return redirect(reverse('booktest:index'))


def logout(request):
    # 使用cookie
    # res = redirect(reverse('booktest:login'))
    # res.delete_cookie('username')
    # return res

    request.session.flush()
    return redirect(reverse('booktest:login'))


def verify(request):
    # 定义变量， 用于画面的背景色、 宽、 高
    global xy
    bgcolor = (random.randrange(20, 100),
               random.randrange(20, 100),
               random.randrange(20, 100))
    width = 100
    height = 35
    # 创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 300):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABqwertCD1iop23EcmFGasdfHIJK456LMNhjkOPQgR8S7vbn9TUVzWXxYZ0yul'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]

    cache.set('rand_str', rand_str)
    # 构造字体对象
    font = ImageFont.truetype('BAUHS93.TTF', 23)
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    # 释放画笔
    del draw
    request.session['verifycode'] = rand_str
    f = io.BytesIO()
    im.save(f, 'png')
    # 将内存中的图片数据返回给客户端， MIME类型为图片png
    return HttpResponse(f.getvalue(), 'image/png')

demo0/demo1/templates/booktest/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        *{
            list-style: none;
        }
    </style>
</head>
<body>
<div class="container" style="text-align: center">
    <h1>添加书籍</h1>
    <form action="{% url 'booktest:addbook' %}" method="post">
        {% csrf_token %}
        标题：<input type="text" name="title"><br><br>
        <input type="submit" value="添加">
    </form>
</div>


<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</body>
</html>

demo0/demo1/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加英雄</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        *{
            list-style: none;
        }
    </style>
</head>
<body>
<div class="container" style="text-align: center;height: 30px;">
    <h1>《{{ book.title }}》 -- 添加英雄</h1>
    <form action="{% url 'booktest:addhero' book.id %}" method="post">
        {% csrf_token %}
        名字：<input type="text" name="username"><br><br>

        性别：<select name="gender" id="gender">
                <option value="m">男</option>
                <option value="w">女</option>
            </select>
            <br><br>
        技能：<input type="text" name="content"><br><br>
        <input type="submit" value="添加">
    </form>
</div>


<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</body>
</html>

demo0/demo1/templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}
    <title>书籍</title>

    {% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
   <style>
        *{
            list-style: none;
        }
    </style>

</head>
<body>


{% block container %}



{% endblock %}



</body>
</html>

demo0/demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        *{
            list-style: none;
        }
    </style>
</head>
<body>

<div class="container" style="text-align: center">
    <ol class="breadcrumb">
        <li><a href="{% url 'booktest:index' %}">首页</a></li>
        <li><a href="{% url 'booktest:list' %}">列表页</a></li>
        <li class="active">详情页</li>
    </ol>
    <h1>详情页</h1>
    <a href="{% url 'booktest:index' %}">首页</a>
    <br>

    <b>书名：</b>《{{ book.title }}》
    {% if book.heroinfo_set.all %}
    <ul>{% for hero in book.heroinfo_set.all %}
        <li>
            <b>人物：</b>{{ hero.name }}---
            <b>信息：</b>{{ hero.content }}---
            <b>性别：</b>{{ hero.gender }}---
            <!--<select name="gender" id="gender">-->
                <!--<option value="m"></option>-->
                <!--<option value="w"></option>-->
            <!--</select>-->
            <a href="{% url 'booktest:deletehero' hero.id %}">删除</a>
            <br><br>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <b>没有人物</b>
    {% endif %}
    <a href="{% url 'booktest:addhero' book.id %}">添加英雄</a>
</div>


<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</body>
</html>

demo0/demo1/templates/booktest/index.html
{% extends 'booktest/base.html' %}
{% block title%}
<title>首页</title>
    <link rel="stylesheet" href="/static/css/index.css">
    <style>
        *{
            list-style: none;
        }
    </style>
{% endblock %}

 {% block container %}
<div class="div_top">

    <h1>首页</h1>
     {% if username %}

    <h2>用户：<span class="user">{{ username }}</span></h2>
    <a href="{% url 'booktest:logout' %}">退出登录</a>
    <a href="{% url 'booktest:upload' %}">上传图片</a>

    {% else %}
    <h4>还未登录 <a href="{% url 'booktest:login' %}">请登录</a></h4>

    {% endif %}
    <a href="{% url 'booktest:list' %}">列表页</a>
    <br>

</div>
<!--<img src="/static/img/1.jpg">-->


<div id="carousel-example-generic" class="carousel slide" data-ride="carousel"
     style="width:550px; margin:auto;border-radius: 10px;overflow: hidden;">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        {% for a in ads %}

        {% if forloop.counter == 1 %}
        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active">
         </li>
        {% else %}
        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}"></li>

        {% endif %}

        {% endfor %}
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        {% for a in ads %}
        {% if forloop.counter == 1 %}

                <div class="item active">
            <img src="/static/media/{{ a.img }}" alt="...">
            <div class="carousel-caption">
                {{ a.desc }}
            </div>
        </div>

        {% else %}
        <div class="item">
            <img src="/static/media/{{ a.img }}" alt="...">
            <div class="carousel-caption">
                {{ a.desc }}
            </div>
        </div>

        {% endif %}

        {% endfor %}



    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

{% endblock %}

demo0/demo1/templates/booktest/list.html
{% extends 'booktest/base.html' %}
{% block title%}
<title>首页</title>
{% endblock %}

{% block container %}


<div class="container" style="text-align: center">
    <ol class="breadcrumb">
        <li><a href="{% url 'booktest:index' %}">首页</a></li>
        <li class="active">列表页</li>
    </ol>
    <h1>列表页</h1>
    {% for book in books %}

    <li>
        <a href="{% url 'booktest:detail' book.id %}">《{{ book.title }}》</a>
        ---
        <a class="btn btn-danger btn-xs" href="{% url 'booktest:deletebook' book.id %}">删除</a>
        <br><br>
    </li>
    {% endfor %}
    <a href="{% url 'booktest:addbook' %}" class="btn btn-xs btn-success">添加书籍</a>
</div>


{% endblock %}

demo0/demo1/templates/booktest/login.html
{% extends 'booktest/base.html' %}
{% block title%}
<title>登录</title>
<style>
    * {
        list-style: none;
    }
</style>
{% endblock %}

{% block container %}
<div class="container">
    <form action="{% url 'booktest:login' %}" method="post">
        {% csrf_token %}
        <label for="username">用户名</label>{{ lgf.username }}<br>
        <label for="password">密码</label>{{ lgf.password }}
        <div>
            <img src="/verify/" alt="" id="verifyimg">
            <input type="text" name="verifycode">
        </div>

        <br>
        <input type="submit" value="登录">
    </form>
</div>


<script>
    $(function () {

        $('#verifyimg').click(function () {
            $(this).attr('src', '/verify/?t=' + new Date().getTime());
        })
    })


</script>


{% endblock %}

demo0/demo1/templates/booktest/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传图片</title>
</head>
<body>
<form enctype="multipart/form-data" action="{% url 'booktest:upload' %}" method="post">
{% csrf_token %}
    图片描述：<input type="text" name="desc">
    <br>
    添加图片：<input type="file" name="uploadimg">
    <br>
    <input type="submit" value="上传">

</form>
</body>
</html>