demo0/demo3/booktest/urls.py
from django.conf.urls import url
from . import views

app_name = 'booktest'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list/$', views.list, name='list'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^addhero/(\d+)/$', views.addhero, name='addhero'),
    url(r'^delhero/(\d+)/$', views.delhero, name='delhero'),
    url(r'^addbook/$', views.addbook, name='addbook'),
    url(r'^delbook/(\d+)/$', views.delbook, name='delbook'),
]

demo0/demo3/demo3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('booktest.urls', namespace='booktest')),
    url('polls/', include('polls.urls', namespace='polls')),
]

demo0/demo3/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url('^$', views.index, name='index'),
    url('^detail/(\d+)/$', views.detail, name='detail'),
    url('^result/(\d+)/$', views.result, name='result'),
    url('^addpoll/$', views.addpoll, name='addpoll'),
    url('^delpoll/(\d+)/$', views.delpoll, name='delpoll'),

]

demo0/demo3/booktest/models.py
from django.db import models

# Create your models here.

class BookInfo(models.Model):
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class HeroInfo(models.Model):
    name = models.CharField(max_length=20)
    info = models.CharField(max_length=50)
    gender = models.CharField(max_length=10)
    book = models.ForeignKey(BookInfo, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

demo0/demo3/polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Options(models.Model):
    choice = models.CharField(max_length=50)
    vote = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice

demo0/demo3/booktest/views.py
from django.shortcuts import render, redirect,reverse


from .models import *
# Create your views here.

def index(request):
    return render(request, 'booktest/index.html', {})

def detail(request, id):
    book = BookInfo.objects.get(pk=id)
    return render(request, 'booktest/detail.html', {'book': book})

def list(request):
    books = BookInfo.objects.all()
    return render(request, 'booktest/list.html', {'books':books})

def addhero(request, id):
    book = BookInfo.objects.get(pk=id)
    if request.method == 'GET':
        return render(request, 'booktest/addhero.html', {'book': book})
    elif request.method == 'POST':
        hero = HeroInfo()
        hero.name = request.POST.get('name')
        hero.info = request.POST.get('info')
        hero.gender = request.POST.get('gender')
        hero.book = book
        hero.save()
        return redirect(reverse('booktest:detail', args=(book.id, )))


def delhero(request, id):
    hero = HeroInfo.objects.get(pk=id)
    book = hero.book
    hero.delete()
    return redirect(reverse('booktest:detail', args=(book.id,)))

def addbook(request):
    if request.method == 'GET':
        return render(request, 'booktest/addbook.html', {})
    elif request.method == 'POST':
        book = BookInfo()
        book.title = request.POST.get('title')
        book.save()
        return redirect(reverse('booktest:list'))

def delbook(request, id):
    book = BookInfo.objects.get(pk=id)
    book.delete()
    return redirect(reverse('booktest:list'))

demo0/demo3/polls/views.py
from django.shortcuts import render,redirect, reverse
from .models import *
# Create your views here.

def index(reqest):
    questions = Question.objects.all()
    return render(reqest, 'polls/index.html', {'questions': questions})

def detail(request, id):
    question = Question.objects.get(pk=id)
    if request.method == 'GET':
        return render(request, 'polls/detail.html', {'question': question})
    elif request.method == 'POST':
        optionid = request.POST.get('optionid')
        option = Options.objects.get(pk=optionid)
        option.vote += 1
        option.save()
        return redirect(reverse('polls:result', args=(question.id, )))

def result(request, id):
    question = Question.objects.get(pk=id)
    return render(request, 'polls/result.html', {'question': question})


def addpoll(request):
    if request.method == 'GET':
        return render(request, 'polls/addpoll.html', {})

    elif request.method == 'POST':
        # 问题
        question = Question()
        question.title = request.POST.get('question')
        question.save()
        # 选项
        option1 = Options()
        option1.choice = request.POST.get('option1')
        option1.question = question
        option1.save()
        option2 = Options()
        option2.choice = request.POST.get('option2')
        option2.question = question
        option2.save()
        return redirect(reverse('polls:index'))


def delpoll(request, id):
    question = Question.objects.get(pk=id)
    question.delete()
    return redirect(reverse('polls:index'))

demo0/demo3/templates/booktest/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加书籍</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">


</head>
<body>
<form action="{% url 'booktest:addbook' %}" method="post">
    <div>
        <span>书名：</span>
        <input type="text" name="title">
    </div>
    <input type="submit" value="添加">
</form>


<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</body>
</html>

demo0/demo3/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加人物</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">



</head>
<body>
<h3>《{{ book.title }}》</h3>
<form action="{% url 'booktest:addhero' book.id %}" method="post">
        <div>
        <span>名称：</span>
        <input type="text" name="name">
         </div>
         <div>
        <span>信息：</span>
        <input type="text" name="info">
         </div>
        <div>
        <span>性别：</span>
            <select name="gender">
                <option value="男">男</option>
                <option value="女">女</option>
            </select>
        </div>
    <input type="submit" value="提交">
</form>


<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</body>
</html>

demo0/demo3/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        * {
            list-style: none;
            margin: 0;
            padding: 0;
        }

        .detail {
            width: 500px;
            margin: auto;
            border: 1px solid #555;
            background-color: #eee;
            border-radius: 10px;
            padding: 50px;
        }

        .detail h2 {
            text-align: center;
            margin-bottom: 20px;
        }

        .detail li {
            line-height: 40px;
            font-size: 16px;
            margin: 20px;
        }
        .detail a{
            margin:0 20px;
        }
        .btn-success{
            width:100px;
            margin-left: 500px;
            margin-top:50px;
        }
    </style>

</head>
<body>
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'booktest:index' %}">首页</a></li>
        <li><a href="{% url 'booktest:list' %}">列表</a></li>
        <li class="active">详情</li>
    </ol>
    <div class="detail">

        <h2>{{ book.title }}</h2>
        <ul>
            {% for hero in book.heroinfo_set.all %}

            <li>{{ hero.name }}---{{ hero.info }}---{{ hero.gender }}
                <a href="{% url 'booktest:delhero' hero.id %}" class="btn btn-xs btn-danger">删除</a>

            </li>

            {% endfor %}
        </ul>
    </div>

    <a class="btn btn-success" href="{% url 'booktest:addhero' book.id %}">添加人物</a>


</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
</body>
</html>

demo0/demo3/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">


</head>
<body>

<div class="container" style="text-align: center;">
<div style="margin-top: 100px;">
    <a href="{% url 'booktest:list' %}" style="font-size: 20px;">进入列表页</a>
</div>
</div>


<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>

</body>
</html>

demo0/demo3/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        *{
            list-style: none;
            margin: 0;
            padding: 0;
        }

        .book{
            width:400px;
            padding:50px;
            margin:auto;
            border: 1px solid #555;
            border-radius:10px;
            background-color: #eee;
        }
        .book a{
            color: #000;
            font-size: 16px;
            clear:both;

        }
        .book li{
            height: 40px;
        }
        .book a:hover{
            color: #f72722;
        }
        .btn-success{
            width:100px;
            margin-left: 500px;
            margin-top:50px;
        }
    </style>

</head>
<body>
<div class="container">
<ol class="breadcrumb">
        <li><a href="{% url 'booktest:index' %}">首页</a></li>
        <li class="active">列表页</li>
</ol>


<div class='book'>
<ul>
    {% for book in books %}
    <li>
        <a href="{% url 'booktest:detail' book.id %}" >{{ book.title }}</a>
        -------------
        <a href="{% url 'booktest:delbook' book.id %}">删除</a>
    </li>
    {% endfor %}
</ul>

</div>
<a class='btn btn-success' href="{% url 'booktest:addbook' %}">添加书籍</a>




</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
</body>
</html>

demo0/demo3/templates/polls/addpoll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加问题</title>
</head>
<body>
<form action="{% url 'polls:addpoll' %}" method="post">
    <ul>
        <li>
            <span>添加投票</span>
            <input type="text" name="question">
        </li>
        <li>
            <span>添加选项1</span>
            <input type="text" name="option1">
        </li>
        <li>
            <span>添加选项2</span>
            <input type="text" name="option2">
        </li>
    </ul>


    <input type="submit" value="添加">
</form>

</body>
</html>

demo0/demo3/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
</head>
<body>


<h2><a href="{% url 'polls:result' question.id %}">{{ question.title }}</a></h2>
<form action="{% url 'polls:detail' question.id %}" method="post">
<ul>
    {% for option in question.options_set.all %}
    {% if forloop.counter == 1 %}
    <li>
        <input type="radio" value="{{ option.id }}" checked name="optionid">
        {{ option.choice }}
    </li>
    {% else %}
    <li>
        <input type="radio" value="{{ option.id }}" name="optionid">
        {{ option.choice }}
    </li>
    {% endif %}

    {% endfor %}
</ul>
    <input type="submit" value="投票">
</form>

</body>
</html>

demo0/demo3/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票首页</title>
</head>
<body>

<ul>
    {% for question in questions %}

    <li>
        <a href="{% url 'polls:detail' question.id %}">{{ question.title }}</a>
        <a href="{% url 'polls:delpoll' question.id %}">删除</a>
    </li>

    {% endfor %}

</ul>

<a href="{% url 'polls:addpoll' %}">添加投票</a>
</body>
</html>

demo0/demo3/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>结果</title>
</head>
<body>
    <h2>{{ question.title }}</h2>
    <ul>
        {% for option in question.options_set.all %}
        <li>
            {{ option.choice }}---
            {{ option.vote }}票
        </li>

        {% endfor %}
    </ul>
</body>
</html>